[font.normal]
family = "MesloLGS NF"

[colors.bright]
black = "#686868"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#f1f1f0"
yellow = "#f3f99d"

[colors.normal]
black = "#282a36"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#f1f1f0"
yellow = "#f3f99d"

[colors.primary]
background = "#282a36"
foreground = "#eff0eb"

[cursor]
style.shape = "Block"
style.blinking = "Always"

[shell]
program = "/bin/zsh"
